### ISSUE TITLE
ephec doesnt work on Splunk Cloud Indexers

### ISSUE THREAD

**Issue by Bre77** [deductiv/export_everything#48]
When trying to run ephec on a Splunk Cloud Indexer, the search command fails with a error code 1.
`index=_introspection host=idx* | eval index="test" | ephec`
`Streamed search execute failed because: Error in 'ephec' command: External search command exited unexpectedly with non-zero error code 1..`

Pushing this to the search head with the `table` command then makes it work.
`index=_introspection host=idx* | eval index="test" | table index host source sourcetype _time _raw | ephec`

Even with debug logging enabled, nothing is generated in export_everything*.log

Search.log has some stuff

ERROR ChunkedExternProcessor [3920943 ChunkedExternProcessorStderrLogger] - stderr: Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
ERROR ChunkedExternProcessor [3920943 ChunkedExternProcessorStderrLogger] - stderr: BrokenPipeError: [Errno 32] Broken pipe

then much later

ERROR ChunkedExternProcessor [4049898 ChunkedExternProcessorStderrLogger] - stderr: HEC Instance Ready: server_uri=https://xxxxxxxxx/services/collector/event

However that last "error" appears even when its successful.

**Comment by jrzmurray** [comment]
This should be resolved in #51, which may be released in the upcoming weeks. Cloud vetting will take some time after that.

**Comment by jrzmurray** [comment]
Version 2.4.0 has been uploaded to Splunkbase and resolves this issue. It may be some time before it passes (or fails) Cloud vetting.
