### ISSUE TITLE
standard HTTP POST PUT request

### ISSUE THREAD

**Issue by GERandro** [deductiv/export_everything#7]
Hi Deductiv team

great TA, already in use in several deployments.
I am looking currently for a way to craft my own http HEADER and push events via http POST or PUT to custom HTTP endpoints.
Do you see an option to include that custom option inside your TA as well?
My usecase is a ITSM solution to create tickets outside of Splunk.

Thanks

ANDRO

**Comment by jrzmurray** [comment]
Hi @GERandro, thank you for the feedback! We have some big changes coming and those are all on our new github branch, soon to be merged into a new app (this repo name will change).  The current version will be deprecated with the new app (Export Everything) being released to supersede it.  We would be happy to add a new target type as a professional services engagement, or merge a PR with that capability, but have you looked into this app? 
https://splunkbase.splunk.com/app/5520/

Cheers

**Comment by jrzmurray** [comment]
@GERandro is there a specific ITSM solution you're using that you want to export to? Have you looked into the mentioned app?

**Comment by GERandro** [comment]
I used Export Everything TA to sync alerts between two Splunk deployments. For the ITSM API (service-now with custom tables) I utilized the Webhook alert from Splunk to send the events first to logstash (this is my ETL pipeline) and from logstash to ITSM/SNOW. A lot of alert enrichment takes place inside logstash, where I thought it is easier to activate inside logstash...

**Comment by GERandro** [comment]
From my PoV you can close this Issue.
